/* Generated by scripts/gen-compass-icon-manifest.mjs — do not edit by hand */
import type { ComponentType, SVGProps } from 'react';
import AccountMinusOutlineIcon from '@mattermost/compass-icons/components/account-minus-outline';
import AccountMultipleOutlineIcon from '@mattermost/compass-icons/components/account-multiple-outline';
import AccountMultiplePlusOutlineIcon from '@mattermost/compass-icons/components/account-multiple-plus-outline';
import AccountOutlineIcon from '@mattermost/compass-icons/components/account-outline';
import AccountPlusOutlineIcon from '@mattermost/compass-icons/components/account-plus-outline';
import AiSummarizeIcon from '@mattermost/compass-icons/components/ai-summarize';
import AirplaneVariantIcon from '@mattermost/compass-icons/components/airplane-variant';
import AirplaneIcon from '@mattermost/compass-icons/components/airplane';
import AlertCircleOutlineIcon from '@mattermost/compass-icons/components/alert-circle-outline';
import AlertOutlineIcon from '@mattermost/compass-icons/components/alert-outline';
import ApplicationCogIcon from '@mattermost/compass-icons/components/application-cog';
import AppsIcon from '@mattermost/compass-icons/components/apps';
import ArchiveArrowUpOutlineIcon from '@mattermost/compass-icons/components/archive-arrow-up-outline';
import ArchiveLockOutlineIcon from '@mattermost/compass-icons/components/archive-lock-outline';
import ArchiveOutlineIcon from '@mattermost/compass-icons/components/archive-outline';
import ArrowBackIosIcon from '@mattermost/compass-icons/components/arrow-back-ios';
import ArrowCollapseIcon from '@mattermost/compass-icons/components/arrow-collapse';
import ArrowDownBoldCircleOutlineIcon from '@mattermost/compass-icons/components/arrow-down-bold-circle-outline';
import ArrowDownIcon from '@mattermost/compass-icons/components/arrow-down';
import ArrowExpandAllIcon from '@mattermost/compass-icons/components/arrow-expand-all';
import ArrowExpandIcon from '@mattermost/compass-icons/components/arrow-expand';
import ArrowForwardIosIcon from '@mattermost/compass-icons/components/arrow-forward-ios';
import ArrowLeftIcon from '@mattermost/compass-icons/components/arrow-left';
import ArrowRightBoldOutlineIcon from '@mattermost/compass-icons/components/arrow-right-bold-outline';
import ArrowRightIcon from '@mattermost/compass-icons/components/arrow-right';
import ArrowUpBoldCircleOutlineIcon from '@mattermost/compass-icons/components/arrow-up-bold-circle-outline';
import ArrowUpIcon from '@mattermost/compass-icons/components/arrow-up';
import AtIcon from '@mattermost/compass-icons/components/at';
import AutoFixIcon from '@mattermost/compass-icons/components/auto-fix';
import BackspaceOutlineIcon from '@mattermost/compass-icons/components/backspace-outline';
import BasketballIcon from '@mattermost/compass-icons/components/basketball';
import BeachUmbrellaOutlineIcon from '@mattermost/compass-icons/components/beach-umbrella-outline';
import BellOffOutlineIcon from '@mattermost/compass-icons/components/bell-off-outline';
import BellOutlineIcon from '@mattermost/compass-icons/components/bell-outline';
import BellRingOutlineIcon from '@mattermost/compass-icons/components/bell-ring-outline';
import BluetoothIcon from '@mattermost/compass-icons/components/bluetooth';
import BookLockOutlineIcon from '@mattermost/compass-icons/components/book-lock-outline';
import BookOutlineIcon from '@mattermost/compass-icons/components/book-outline';
import BookmarkOutlineIcon from '@mattermost/compass-icons/components/bookmark-outline';
import BookmarkIcon from '@mattermost/compass-icons/components/bookmark';
import BrandGitlabIcon from '@mattermost/compass-icons/components/brand-gitlab';
import BrandGoogleIcon from '@mattermost/compass-icons/components/brand-google';
import BrandOffice365Icon from '@mattermost/compass-icons/components/brand-office-365';
import BrandOneLoginIcon from '@mattermost/compass-icons/components/brand-one-login';
import BrandZoomIcon from '@mattermost/compass-icons/components/brand-zoom';
import BullhornOutlineIcon from '@mattermost/compass-icons/components/bullhorn-outline';
import CalendarCheckOutlineIcon from '@mattermost/compass-icons/components/calendar-check-outline';
import CalendarMonthOutlineIcon from '@mattermost/compass-icons/components/calendar-month-outline';
import CalendarOutlineIcon from '@mattermost/compass-icons/components/calendar-outline';
import CameraOutlineIcon from '@mattermost/compass-icons/components/camera-outline';
import CancelIcon from '@mattermost/compass-icons/components/cancel';
import CarOutlineIcon from '@mattermost/compass-icons/components/car-outline';
import CellphoneIcon from '@mattermost/compass-icons/components/cellphone';
import ChartBarIcon from '@mattermost/compass-icons/components/chart-bar';
import ChartLineIcon from '@mattermost/compass-icons/components/chart-line';
import CheckAllIcon from '@mattermost/compass-icons/components/check-all';
import CheckCircleOutlineIcon from '@mattermost/compass-icons/components/check-circle-outline';
import CheckCircleIcon from '@mattermost/compass-icons/components/check-circle';
import CheckIcon from '@mattermost/compass-icons/components/check';
import CheckboxBlankOutlineIcon from '@mattermost/compass-icons/components/checkbox-blank-outline';
import CheckboxMarkedCircleOutlineIcon from '@mattermost/compass-icons/components/checkbox-marked-circle-outline';
import CheckboxMarkedIcon from '@mattermost/compass-icons/components/checkbox-marked';
import CheckboxMultipleMarkedOutlineIcon from '@mattermost/compass-icons/components/checkbox-multiple-marked-outline';
import ChevronDownCircleOutlineIcon from '@mattermost/compass-icons/components/chevron-down-circle-outline';
import ChevronDownIcon from '@mattermost/compass-icons/components/chevron-down';
import ChevronLeftIcon from '@mattermost/compass-icons/components/chevron-left';
import ChevronRightIcon from '@mattermost/compass-icons/components/chevron-right';
import ChevronUpIcon from '@mattermost/compass-icons/components/chevron-up';
import CircleMultipleOutlineLockIcon from '@mattermost/compass-icons/components/circle-multiple-outline-lock';
import CircleMultipleOutlineIcon from '@mattermost/compass-icons/components/circle-multiple-outline';
import CircleOutlineIcon from '@mattermost/compass-icons/components/circle-outline';
import ClockOutlineIcon from '@mattermost/compass-icons/components/clock-outline';
import ClockSendOutlineIcon from '@mattermost/compass-icons/components/clock-send-outline';
import ClockIcon from '@mattermost/compass-icons/components/clock';
import CloseCircleOutlineIcon from '@mattermost/compass-icons/components/close-circle-outline';
import CloseCircleIcon from '@mattermost/compass-icons/components/close-circle';
import CloseIcon from '@mattermost/compass-icons/components/close';
import ClosedCaptionOutlineIcon from '@mattermost/compass-icons/components/closed-caption-outline';
import CodeBlockIcon from '@mattermost/compass-icons/components/code-block';
import CodeBracketsIcon from '@mattermost/compass-icons/components/code-brackets';
import CodeTagsIcon from '@mattermost/compass-icons/components/code-tags';
import CogOutlineIcon from '@mattermost/compass-icons/components/cog-outline';
import ConditionBranchIcon from '@mattermost/compass-icons/components/condition-branch';
import ConsoleIcon from '@mattermost/compass-icons/components/console';
import ContentCopyIcon from '@mattermost/compass-icons/components/content-copy';
import CreationOutlineIcon from '@mattermost/compass-icons/components/creation-outline';
import CreditCardOutlineIcon from '@mattermost/compass-icons/components/credit-card-outline';
import CrownOutlineIcon from '@mattermost/compass-icons/components/crown-outline';
import CurrencyUsdIcon from '@mattermost/compass-icons/components/currency-usd';
import DialpadIcon from '@mattermost/compass-icons/components/dialpad';
import DockLeftIcon from '@mattermost/compass-icons/components/dock-left';
import DockWindowIcon from '@mattermost/compass-icons/components/dock-window';
import DotsHorizontalIcon from '@mattermost/compass-icons/components/dots-horizontal';
import DotsVerticalIcon from '@mattermost/compass-icons/components/dots-vertical';
import DownloadOutlineIcon from '@mattermost/compass-icons/components/download-outline';
import DragVerticalIcon from '@mattermost/compass-icons/components/drag-vertical';
import DrawIcon from '@mattermost/compass-icons/components/draw';
import ElementOfIcon from '@mattermost/compass-icons/components/element-of';
import EmailOutlineIcon from '@mattermost/compass-icons/components/email-outline';
import EmailPlusOutlineIcon from '@mattermost/compass-icons/components/email-plus-outline';
import EmailVariantIcon from '@mattermost/compass-icons/components/email-variant';
import EmoticonCustomOutlineIcon from '@mattermost/compass-icons/components/emoticon-custom-outline';
import EmoticonHappyOutlineIcon from '@mattermost/compass-icons/components/emoticon-happy-outline';
import EmoticonOutlineIcon from '@mattermost/compass-icons/components/emoticon-outline';
import EmoticonPlusOutlineIcon from '@mattermost/compass-icons/components/emoticon-plus-outline';
import EqualIcon from '@mattermost/compass-icons/components/equal';
import ExclamationThickIcon from '@mattermost/compass-icons/components/exclamation-thick';
import ExitToAppIcon from '@mattermost/compass-icons/components/exit-to-app';
import ExportVariantIcon from '@mattermost/compass-icons/components/export-variant';
import EyeOffOutlineIcon from '@mattermost/compass-icons/components/eye-off-outline';
import EyeOutlineIcon from '@mattermost/compass-icons/components/eye-outline';
import FileAudioOutlineLargeIcon from '@mattermost/compass-icons/components/file-audio-outline-large';
import FileAudioOutlineIcon from '@mattermost/compass-icons/components/file-audio-outline';
import FileCodeOutlineLargeIcon from '@mattermost/compass-icons/components/file-code-outline-large';
import FileCodeOutlineIcon from '@mattermost/compass-icons/components/file-code-outline';
import FileExcelOutlineLargeIcon from '@mattermost/compass-icons/components/file-excel-outline-large';
import FileExcelOutlineIcon from '@mattermost/compass-icons/components/file-excel-outline';
import FileGenericOutlineLargeIcon from '@mattermost/compass-icons/components/file-generic-outline-large';
import FileGenericOutlineIcon from '@mattermost/compass-icons/components/file-generic-outline';
import FileGifIcon from '@mattermost/compass-icons/components/file-gif';
import FileHelpOutlineLargeIcon from '@mattermost/compass-icons/components/file-help-outline-large';
import FileImageBrokenOutlineLargeIcon from '@mattermost/compass-icons/components/file-image-broken-outline-large';
import FileImageBrokenOutlineIcon from '@mattermost/compass-icons/components/file-image-broken-outline';
import FileImageOutlineLargeIcon from '@mattermost/compass-icons/components/file-image-outline-large';
import FileImageOutlineIcon from '@mattermost/compass-icons/components/file-image-outline';
import FileMultipleOutlineLargeIcon from '@mattermost/compass-icons/components/file-multiple-outline-large';
import FileMultipleOutlineIcon from '@mattermost/compass-icons/components/file-multiple-outline';
import FilePatchOutlineLargeIcon from '@mattermost/compass-icons/components/file-patch-outline-large';
import FilePatchOutlineIcon from '@mattermost/compass-icons/components/file-patch-outline';
import FilePdfOutlineLargeIcon from '@mattermost/compass-icons/components/file-pdf-outline-large';
import FilePdfOutlineIcon from '@mattermost/compass-icons/components/file-pdf-outline';
import FilePowerpointOutlineLargeIcon from '@mattermost/compass-icons/components/file-powerpoint-outline-large';
import FilePowerpointOutlineIcon from '@mattermost/compass-icons/components/file-powerpoint-outline';
import FileTextOutlineLargeIcon from '@mattermost/compass-icons/components/file-text-outline-large';
import FileTextOutlineIcon from '@mattermost/compass-icons/components/file-text-outline';
import FileVideoOutlineLargeIcon from '@mattermost/compass-icons/components/file-video-outline-large';
import FileVideoOutlineIcon from '@mattermost/compass-icons/components/file-video-outline';
import FileWordOutlineLargeIcon from '@mattermost/compass-icons/components/file-word-outline-large';
import FileWordOutlineIcon from '@mattermost/compass-icons/components/file-word-outline';
import FileZipOutlineLargeIcon from '@mattermost/compass-icons/components/file-zip-outline-large';
import FileZipOutlineIcon from '@mattermost/compass-icons/components/file-zip-outline';
import FilterVariantIcon from '@mattermost/compass-icons/components/filter-variant';
import FireIcon from '@mattermost/compass-icons/components/fire';
import FlagCheckeredIcon from '@mattermost/compass-icons/components/flag-checkered';
import FlagOutlineIcon from '@mattermost/compass-icons/components/flag-outline';
import FlagIcon from '@mattermost/compass-icons/components/flag';
import FlaskOutlineIcon from '@mattermost/compass-icons/components/flask-outline';
import FolderMoveOutlineIcon from '@mattermost/compass-icons/components/folder-move-outline';
import FolderOutlineIcon from '@mattermost/compass-icons/components/folder-outline';
import FolderPlusOutlineIcon from '@mattermost/compass-icons/components/folder-plus-outline';
import FoodAppleIcon from '@mattermost/compass-icons/components/food-apple';
import FoodForkDrinkIcon from '@mattermost/compass-icons/components/food-fork-drink';
import FormatBoldIcon from '@mattermost/compass-icons/components/format-bold';
import FormatClearIcon from '@mattermost/compass-icons/components/format-clear';
import FormatHeader1Icon from '@mattermost/compass-icons/components/format-header-1';
import FormatHeader2Icon from '@mattermost/compass-icons/components/format-header-2';
import FormatHeader3Icon from '@mattermost/compass-icons/components/format-header-3';
import FormatHeader4Icon from '@mattermost/compass-icons/components/format-header-4';
import FormatHeader5Icon from '@mattermost/compass-icons/components/format-header-5';
import FormatHeader6Icon from '@mattermost/compass-icons/components/format-header-6';
import FormatHeaderIcon from '@mattermost/compass-icons/components/format-header';
import FormatItalicIcon from '@mattermost/compass-icons/components/format-italic';
import FormatLetterCaseIcon from '@mattermost/compass-icons/components/format-letter-case';
import FormatListBulletedIcon from '@mattermost/compass-icons/components/format-list-bulleted';
import FormatListNumberedIcon from '@mattermost/compass-icons/components/format-list-numbered';
import FormatQuoteOpenIcon from '@mattermost/compass-icons/components/format-quote-open';
import FormatStrikethroughVariantIcon from '@mattermost/compass-icons/components/format-strikethrough-variant';
import ForumOutlineIcon from '@mattermost/compass-icons/components/forum-outline';
import FunctionIcon from '@mattermost/compass-icons/components/function';
import GfycatIcon from '@mattermost/compass-icons/components/gfycat';
import GithubCircleIcon from '@mattermost/compass-icons/components/github-circle';
import GlassesIcon from '@mattermost/compass-icons/components/glasses';
import GlobeCheckedIcon from '@mattermost/compass-icons/components/globe-checked';
import GlobeIcon from '@mattermost/compass-icons/components/globe';
import HammerIcon from '@mattermost/compass-icons/components/hammer';
import HandRightOutlineOffIcon from '@mattermost/compass-icons/components/hand-right-outline-off';
import HandRightOutlineIcon from '@mattermost/compass-icons/components/hand-right-outline';
import HandRightIcon from '@mattermost/compass-icons/components/hand-right';
import HeadphonesIcon from '@mattermost/compass-icons/components/headphones';
import HeartOutlineIcon from '@mattermost/compass-icons/components/heart-outline';
import HelpCircleOutlineIcon from '@mattermost/compass-icons/components/help-circle-outline';
import HelpIcon from '@mattermost/compass-icons/components/help';
import HomeVariantOutlineIcon from '@mattermost/compass-icons/components/home-variant-outline';
import IconBrandGiphyIcon from '@mattermost/compass-icons/components/icon-brand-giphy';
import IframeListOutlineIcon from '@mattermost/compass-icons/components/iframe-list-outline';
import ImageAreaOutlineIcon from '@mattermost/compass-icons/components/image-area-outline';
import ImageBrokenOutlineIcon from '@mattermost/compass-icons/components/image-broken-outline';
import ImageOutlineIcon from '@mattermost/compass-icons/components/image-outline';
import ImportIcon from '@mattermost/compass-icons/components/import';
import InfinityIcon from '@mattermost/compass-icons/components/infinity';
import InformationOutlineIcon from '@mattermost/compass-icons/components/information-outline';
import KanbanIcon from '@mattermost/compass-icons/components/kanban';
import KeyVariantCircleIcon from '@mattermost/compass-icons/components/key-variant-circle';
import KeyVariantIcon from '@mattermost/compass-icons/components/key-variant';
import KeyboardOutlineIcon from '@mattermost/compass-icons/components/keyboard-outline';
import KeyboardReturnIcon from '@mattermost/compass-icons/components/keyboard-return';
import LaptopIcon from '@mattermost/compass-icons/components/laptop';
import LayersOutlineIcon from '@mattermost/compass-icons/components/layers-outline';
import LeafOutlineIcon from '@mattermost/compass-icons/components/leaf-outline';
import LeafIcon from '@mattermost/compass-icons/components/leaf';
import LightbulbOutlineIcon from '@mattermost/compass-icons/components/lightbulb-outline';
import LightningBoltOutlineIcon from '@mattermost/compass-icons/components/lightning-bolt-outline';
import LinkVariantOffIcon from '@mattermost/compass-icons/components/link-variant-off';
import LinkVariantIcon from '@mattermost/compass-icons/components/link-variant';
import LockOutlineIcon from '@mattermost/compass-icons/components/lock-outline';
import LockIcon from '@mattermost/compass-icons/components/lock';
import LogoutVariantIcon from '@mattermost/compass-icons/components/logout-variant';
import MagnifyMinusIcon from '@mattermost/compass-icons/components/magnify-minus';
import MagnifyPlusIcon from '@mattermost/compass-icons/components/magnify-plus';
import MagnifyIcon from '@mattermost/compass-icons/components/magnify';
import MapMarkerOutlineIcon from '@mattermost/compass-icons/components/map-marker-outline';
import MarkAsUnreadIcon from '@mattermost/compass-icons/components/mark-as-unread';
import MattermostIcon from '@mattermost/compass-icons/components/mattermost';
import MenuDownIcon from '@mattermost/compass-icons/components/menu-down';
import MenuLeftIcon from '@mattermost/compass-icons/components/menu-left';
import MenuRightIcon from '@mattermost/compass-icons/components/menu-right';
import MenuUpIcon from '@mattermost/compass-icons/components/menu-up';
import MenuVariantIcon from '@mattermost/compass-icons/components/menu-variant';
import MenuIcon from '@mattermost/compass-icons/components/menu';
import MessageArrowRightOutlineIcon from '@mattermost/compass-icons/components/message-arrow-right-outline';
import MessageCheckOutlineIcon from '@mattermost/compass-icons/components/message-check-outline';
import MessageCheckIcon from '@mattermost/compass-icons/components/message-check';
import MessageMinusOutlineIcon from '@mattermost/compass-icons/components/message-minus-outline';
import MessagePlusOutlineIcon from '@mattermost/compass-icons/components/message-plus-outline';
import MessageTextOutlineIcon from '@mattermost/compass-icons/components/message-text-outline';
import MicrophoneOffIcon from '@mattermost/compass-icons/components/microphone-off';
import MicrophoneOutlineIcon from '@mattermost/compass-icons/components/microphone-outline';
import MicrophoneIcon from '@mattermost/compass-icons/components/microphone';
import MinusBoxIcon from '@mattermost/compass-icons/components/minus-box';
import MinusCircleOutlineIcon from '@mattermost/compass-icons/components/minus-circle-outline';
import MinusCircleIcon from '@mattermost/compass-icons/components/minus-circle';
import MinusIcon from '@mattermost/compass-icons/components/minus';
import MonitorAccountIcon from '@mattermost/compass-icons/components/monitor-account';
import MonitorOffIcon from '@mattermost/compass-icons/components/monitor-off';
import MonitorShareIcon from '@mattermost/compass-icons/components/monitor-share';
import MonitorIcon from '@mattermost/compass-icons/components/monitor';
import NotEqualVariantIcon from '@mattermost/compass-icons/components/not-equal-variant';
import NotebookOutlineIcon from '@mattermost/compass-icons/components/notebook-outline';
import OauthIcon from '@mattermost/compass-icons/components/oauth';
import OpenInNewIcon from '@mattermost/compass-icons/components/open-in-new';
import PaletteOutlineIcon from '@mattermost/compass-icons/components/palette-outline';
import PaperclipIcon from '@mattermost/compass-icons/components/paperclip';
import PauseIcon from '@mattermost/compass-icons/components/pause';
import PencilOutlineIcon from '@mattermost/compass-icons/components/pencil-outline';
import PhoneHangupIcon from '@mattermost/compass-icons/components/phone-hangup';
import PhoneInTalkIcon from '@mattermost/compass-icons/components/phone-in-talk';
import PhoneOutlineIcon from '@mattermost/compass-icons/components/phone-outline';
import PhoneIcon from '@mattermost/compass-icons/components/phone';
import PinOutlineIcon from '@mattermost/compass-icons/components/pin-outline';
import PinIcon from '@mattermost/compass-icons/components/pin';
import PlayBoxMultipleOutlineIcon from '@mattermost/compass-icons/components/play-box-multiple-outline';
import PlayOutlineIcon from '@mattermost/compass-icons/components/play-outline';
import PlayIcon from '@mattermost/compass-icons/components/play';
import PlaylistCheckIcon from '@mattermost/compass-icons/components/playlist-check';
import PlusBoxOutlineIcon from '@mattermost/compass-icons/components/plus-box-outline';
import PlusBoxIcon from '@mattermost/compass-icons/components/plus-box';
import PlusIcon from '@mattermost/compass-icons/components/plus';
import PoundIcon from '@mattermost/compass-icons/components/pound';
import PowerPlugOutlineIcon from '@mattermost/compass-icons/components/power-plug-outline';
import ProductBoardsIcon from '@mattermost/compass-icons/components/product-boards';
import ProductChannelsIcon from '@mattermost/compass-icons/components/product-channels';
import ProductPlaybooksIcon from '@mattermost/compass-icons/components/product-playbooks';
import ProductsIcon from '@mattermost/compass-icons/components/products';
import RadioboxBlankIcon from '@mattermost/compass-icons/components/radiobox-blank';
import RadioboxMarkedIcon from '@mattermost/compass-icons/components/radiobox-marked';
import RecordCircleOutlineIcon from '@mattermost/compass-icons/components/record-circle-outline';
import RecordSquareOutlineIcon from '@mattermost/compass-icons/components/record-square-outline';
import RefreshIcon from '@mattermost/compass-icons/components/refresh';
import ReplyOutlineIcon from '@mattermost/compass-icons/components/reply-outline';
import ResizeBottomRightIcon from '@mattermost/compass-icons/components/resize-bottom-right';
import RestoreIcon from '@mattermost/compass-icons/components/restore';
import RobotHappyIcon from '@mattermost/compass-icons/components/robot-happy';
import SearchListIcon from '@mattermost/compass-icons/components/search-list';
import SendOutlineIcon from '@mattermost/compass-icons/components/send-outline';
import SendIcon from '@mattermost/compass-icons/components/send';
import ServerOutlineIcon from '@mattermost/compass-icons/components/server-outline';
import ServerVariantPlusIcon from '@mattermost/compass-icons/components/server-variant-plus';
import ServerVariantIcon from '@mattermost/compass-icons/components/server-variant';
import SettingsOutlineIcon from '@mattermost/compass-icons/components/settings-outline';
import ShareVariantOutlineIcon from '@mattermost/compass-icons/components/share-variant-outline';
import ShieldAlertOutlineIcon from '@mattermost/compass-icons/components/shield-alert-outline';
import ShieldCheckIcon from '@mattermost/compass-icons/components/shield-check';
import ShieldLockOutlineIcon from '@mattermost/compass-icons/components/shield-lock-outline';
import ShieldOutlineIcon from '@mattermost/compass-icons/components/shield-outline';
import ShuffleVariantIcon from '@mattermost/compass-icons/components/shuffle-variant';
import SitemapIcon from '@mattermost/compass-icons/components/sitemap';
import SlashForwardBoxOutlineIcon from '@mattermost/compass-icons/components/slash-forward-box-outline';
import SlashForwardIcon from '@mattermost/compass-icons/components/slash-forward';
import SoccerIcon from '@mattermost/compass-icons/components/soccer';
import SortAlphabeticalAscendingIcon from '@mattermost/compass-icons/components/sort-alphabetical-ascending';
import SortAscendingIcon from '@mattermost/compass-icons/components/sort-ascending';
import SourceBranchIcon from '@mattermost/compass-icons/components/source-branch';
import SourcePullIcon from '@mattermost/compass-icons/components/source-pull';
import SpellcheckIcon from '@mattermost/compass-icons/components/spellcheck';
import SquareIcon from '@mattermost/compass-icons/components/square';
import StarOutlineIcon from '@mattermost/compass-icons/components/star-outline';
import StarIcon from '@mattermost/compass-icons/components/star';
import SyncIcon from '@mattermost/compass-icons/components/sync';
import TableColumnPlusAfterIcon from '@mattermost/compass-icons/components/table-column-plus-after';
import TableColumnPlusBeforeIcon from '@mattermost/compass-icons/components/table-column-plus-before';
import TableColumnRemoveIcon from '@mattermost/compass-icons/components/table-column-remove';
import TableLargeIcon from '@mattermost/compass-icons/components/table-large';
import TablePlusIcon from '@mattermost/compass-icons/components/table-plus';
import TableRemoveIcon from '@mattermost/compass-icons/components/table-remove';
import TableRowPlusAfterIcon from '@mattermost/compass-icons/components/table-row-plus-after';
import TableRowPlusBeforeIcon from '@mattermost/compass-icons/components/table-row-plus-before';
import TableRowRemoveIcon from '@mattermost/compass-icons/components/table-row-remove';
import TableSettingsIcon from '@mattermost/compass-icons/components/table-settings';
import TabletIcon from '@mattermost/compass-icons/components/tablet';
import TextBoxOutlineIcon from '@mattermost/compass-icons/components/text-box-outline';
import TextLongIcon from '@mattermost/compass-icons/components/text-long';
import TextShortIcon from '@mattermost/compass-icons/components/text-short';
import ThumbsUpDownIcon from '@mattermost/compass-icons/components/thumbs-up-down';
import TimelineTextOutlineIcon from '@mattermost/compass-icons/components/timeline-text-outline';
import TranslateIcon from '@mattermost/compass-icons/components/translate';
import TrashCanOutlineIcon from '@mattermost/compass-icons/components/trash-can-outline';
import TuneIcon from '@mattermost/compass-icons/components/tune';
import UpdateIcon from '@mattermost/compass-icons/components/update';
import UploadOutlineIcon from '@mattermost/compass-icons/components/upload-outline';
import VideoOffOutlineIcon from '@mattermost/compass-icons/components/video-off-outline';
import VideoOutlineIcon from '@mattermost/compass-icons/components/video-outline';
import ViewGridPlusOutlineIcon from '@mattermost/compass-icons/components/view-grid-plus-outline';
import VolumeHighIcon from '@mattermost/compass-icons/components/volume-high';
import WebhookIncomingIcon from '@mattermost/compass-icons/components/webhook-incoming';
import WebhookOutgoingIcon from '@mattermost/compass-icons/components/webhook-outgoing';
import WebhookIcon from '@mattermost/compass-icons/components/webhook';

export type CompassSvgIcon = ComponentType<
  SVGProps<SVGSVGElement> & { size?: string | number }
>;

export const STORYBOOK_ICONS = {
  'account-minus-outline': AccountMinusOutlineIcon,
  'account-multiple-outline': AccountMultipleOutlineIcon,
  'account-multiple-plus-outline': AccountMultiplePlusOutlineIcon,
  'account-outline': AccountOutlineIcon,
  'account-plus-outline': AccountPlusOutlineIcon,
  'ai-summarize': AiSummarizeIcon,
  'airplane-variant': AirplaneVariantIcon,
  'airplane': AirplaneIcon,
  'alert-circle-outline': AlertCircleOutlineIcon,
  'alert-outline': AlertOutlineIcon,
  'application-cog': ApplicationCogIcon,
  'apps': AppsIcon,
  'archive-arrow-up-outline': ArchiveArrowUpOutlineIcon,
  'archive-lock-outline': ArchiveLockOutlineIcon,
  'archive-outline': ArchiveOutlineIcon,
  'arrow-back-ios': ArrowBackIosIcon,
  'arrow-collapse': ArrowCollapseIcon,
  'arrow-down-bold-circle-outline': ArrowDownBoldCircleOutlineIcon,
  'arrow-down': ArrowDownIcon,
  'arrow-expand-all': ArrowExpandAllIcon,
  'arrow-expand': ArrowExpandIcon,
  'arrow-forward-ios': ArrowForwardIosIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-right-bold-outline': ArrowRightBoldOutlineIcon,
  'arrow-right': ArrowRightIcon,
  'arrow-up-bold-circle-outline': ArrowUpBoldCircleOutlineIcon,
  'arrow-up': ArrowUpIcon,
  'at': AtIcon,
  'auto-fix': AutoFixIcon,
  'backspace-outline': BackspaceOutlineIcon,
  'basketball': BasketballIcon,
  'beach-umbrella-outline': BeachUmbrellaOutlineIcon,
  'bell-off-outline': BellOffOutlineIcon,
  'bell-outline': BellOutlineIcon,
  'bell-ring-outline': BellRingOutlineIcon,
  'bluetooth': BluetoothIcon,
  'book-lock-outline': BookLockOutlineIcon,
  'book-outline': BookOutlineIcon,
  'bookmark-outline': BookmarkOutlineIcon,
  'bookmark': BookmarkIcon,
  'brand-gitlab': BrandGitlabIcon,
  'brand-google': BrandGoogleIcon,
  'brand-office-365': BrandOffice365Icon,
  'brand-one-login': BrandOneLoginIcon,
  'brand-zoom': BrandZoomIcon,
  'bullhorn-outline': BullhornOutlineIcon,
  'calendar-check-outline': CalendarCheckOutlineIcon,
  'calendar-month-outline': CalendarMonthOutlineIcon,
  'calendar-outline': CalendarOutlineIcon,
  'camera-outline': CameraOutlineIcon,
  'cancel': CancelIcon,
  'car-outline': CarOutlineIcon,
  'cellphone': CellphoneIcon,
  'chart-bar': ChartBarIcon,
  'chart-line': ChartLineIcon,
  'check-all': CheckAllIcon,
  'check-circle-outline': CheckCircleOutlineIcon,
  'check-circle': CheckCircleIcon,
  'check': CheckIcon,
  'checkbox-blank-outline': CheckboxBlankOutlineIcon,
  'checkbox-marked-circle-outline': CheckboxMarkedCircleOutlineIcon,
  'checkbox-marked': CheckboxMarkedIcon,
  'checkbox-multiple-marked-outline': CheckboxMultipleMarkedOutlineIcon,
  'chevron-down-circle-outline': ChevronDownCircleOutlineIcon,
  'chevron-down': ChevronDownIcon,
  'chevron-left': ChevronLeftIcon,
  'chevron-right': ChevronRightIcon,
  'chevron-up': ChevronUpIcon,
  'circle-multiple-outline-lock': CircleMultipleOutlineLockIcon,
  'circle-multiple-outline': CircleMultipleOutlineIcon,
  'circle-outline': CircleOutlineIcon,
  'clock-outline': ClockOutlineIcon,
  'clock-send-outline': ClockSendOutlineIcon,
  'clock': ClockIcon,
  'close-circle-outline': CloseCircleOutlineIcon,
  'close-circle': CloseCircleIcon,
  'close': CloseIcon,
  'closed-caption-outline': ClosedCaptionOutlineIcon,
  'code-block': CodeBlockIcon,
  'code-brackets': CodeBracketsIcon,
  'code-tags': CodeTagsIcon,
  'cog-outline': CogOutlineIcon,
  'condition-branch': ConditionBranchIcon,
  'console': ConsoleIcon,
  'content-copy': ContentCopyIcon,
  'creation-outline': CreationOutlineIcon,
  'credit-card-outline': CreditCardOutlineIcon,
  'crown-outline': CrownOutlineIcon,
  'currency-usd': CurrencyUsdIcon,
  'dialpad': DialpadIcon,
  'dock-left': DockLeftIcon,
  'dock-window': DockWindowIcon,
  'dots-horizontal': DotsHorizontalIcon,
  'dots-vertical': DotsVerticalIcon,
  'download-outline': DownloadOutlineIcon,
  'drag-vertical': DragVerticalIcon,
  'draw': DrawIcon,
  'element-of': ElementOfIcon,
  'email-outline': EmailOutlineIcon,
  'email-plus-outline': EmailPlusOutlineIcon,
  'email-variant': EmailVariantIcon,
  'emoticon-custom-outline': EmoticonCustomOutlineIcon,
  'emoticon-happy-outline': EmoticonHappyOutlineIcon,
  'emoticon-outline': EmoticonOutlineIcon,
  'emoticon-plus-outline': EmoticonPlusOutlineIcon,
  'equal': EqualIcon,
  'exclamation-thick': ExclamationThickIcon,
  'exit-to-app': ExitToAppIcon,
  'export-variant': ExportVariantIcon,
  'eye-off-outline': EyeOffOutlineIcon,
  'eye-outline': EyeOutlineIcon,
  'file-audio-outline-large': FileAudioOutlineLargeIcon,
  'file-audio-outline': FileAudioOutlineIcon,
  'file-code-outline-large': FileCodeOutlineLargeIcon,
  'file-code-outline': FileCodeOutlineIcon,
  'file-excel-outline-large': FileExcelOutlineLargeIcon,
  'file-excel-outline': FileExcelOutlineIcon,
  'file-generic-outline-large': FileGenericOutlineLargeIcon,
  'file-generic-outline': FileGenericOutlineIcon,
  'file-gif': FileGifIcon,
  'file-help-outline-large': FileHelpOutlineLargeIcon,
  'file-image-broken-outline-large': FileImageBrokenOutlineLargeIcon,
  'file-image-broken-outline': FileImageBrokenOutlineIcon,
  'file-image-outline-large': FileImageOutlineLargeIcon,
  'file-image-outline': FileImageOutlineIcon,
  'file-multiple-outline-large': FileMultipleOutlineLargeIcon,
  'file-multiple-outline': FileMultipleOutlineIcon,
  'file-patch-outline-large': FilePatchOutlineLargeIcon,
  'file-patch-outline': FilePatchOutlineIcon,
  'file-pdf-outline-large': FilePdfOutlineLargeIcon,
  'file-pdf-outline': FilePdfOutlineIcon,
  'file-powerpoint-outline-large': FilePowerpointOutlineLargeIcon,
  'file-powerpoint-outline': FilePowerpointOutlineIcon,
  'file-text-outline-large': FileTextOutlineLargeIcon,
  'file-text-outline': FileTextOutlineIcon,
  'file-video-outline-large': FileVideoOutlineLargeIcon,
  'file-video-outline': FileVideoOutlineIcon,
  'file-word-outline-large': FileWordOutlineLargeIcon,
  'file-word-outline': FileWordOutlineIcon,
  'file-zip-outline-large': FileZipOutlineLargeIcon,
  'file-zip-outline': FileZipOutlineIcon,
  'filter-variant': FilterVariantIcon,
  'fire': FireIcon,
  'flag-checkered': FlagCheckeredIcon,
  'flag-outline': FlagOutlineIcon,
  'flag': FlagIcon,
  'flask-outline': FlaskOutlineIcon,
  'folder-move-outline': FolderMoveOutlineIcon,
  'folder-outline': FolderOutlineIcon,
  'folder-plus-outline': FolderPlusOutlineIcon,
  'food-apple': FoodAppleIcon,
  'food-fork-drink': FoodForkDrinkIcon,
  'format-bold': FormatBoldIcon,
  'format-clear': FormatClearIcon,
  'format-header-1': FormatHeader1Icon,
  'format-header-2': FormatHeader2Icon,
  'format-header-3': FormatHeader3Icon,
  'format-header-4': FormatHeader4Icon,
  'format-header-5': FormatHeader5Icon,
  'format-header-6': FormatHeader6Icon,
  'format-header': FormatHeaderIcon,
  'format-italic': FormatItalicIcon,
  'format-letter-case': FormatLetterCaseIcon,
  'format-list-bulleted': FormatListBulletedIcon,
  'format-list-numbered': FormatListNumberedIcon,
  'format-quote-open': FormatQuoteOpenIcon,
  'format-strikethrough-variant': FormatStrikethroughVariantIcon,
  'forum-outline': ForumOutlineIcon,
  'function': FunctionIcon,
  'gfycat': GfycatIcon,
  'github-circle': GithubCircleIcon,
  'glasses': GlassesIcon,
  'globe-checked': GlobeCheckedIcon,
  'globe': GlobeIcon,
  'hammer': HammerIcon,
  'hand-right-outline-off': HandRightOutlineOffIcon,
  'hand-right-outline': HandRightOutlineIcon,
  'hand-right': HandRightIcon,
  'headphones': HeadphonesIcon,
  'heart-outline': HeartOutlineIcon,
  'help-circle-outline': HelpCircleOutlineIcon,
  'help': HelpIcon,
  'home-variant-outline': HomeVariantOutlineIcon,
  'icon-brand-giphy': IconBrandGiphyIcon,
  'iframe-list-outline': IframeListOutlineIcon,
  'image-area-outline': ImageAreaOutlineIcon,
  'image-broken-outline': ImageBrokenOutlineIcon,
  'image-outline': ImageOutlineIcon,
  'import': ImportIcon,
  'infinity': InfinityIcon,
  'information-outline': InformationOutlineIcon,
  'kanban': KanbanIcon,
  'key-variant-circle': KeyVariantCircleIcon,
  'key-variant': KeyVariantIcon,
  'keyboard-outline': KeyboardOutlineIcon,
  'keyboard-return': KeyboardReturnIcon,
  'laptop': LaptopIcon,
  'layers-outline': LayersOutlineIcon,
  'leaf-outline': LeafOutlineIcon,
  'leaf': LeafIcon,
  'lightbulb-outline': LightbulbOutlineIcon,
  'lightning-bolt-outline': LightningBoltOutlineIcon,
  'link-variant-off': LinkVariantOffIcon,
  'link-variant': LinkVariantIcon,
  'lock-outline': LockOutlineIcon,
  'lock': LockIcon,
  'logout-variant': LogoutVariantIcon,
  'magnify-minus': MagnifyMinusIcon,
  'magnify-plus': MagnifyPlusIcon,
  'magnify': MagnifyIcon,
  'map-marker-outline': MapMarkerOutlineIcon,
  'mark-as-unread': MarkAsUnreadIcon,
  'mattermost': MattermostIcon,
  'menu-down': MenuDownIcon,
  'menu-left': MenuLeftIcon,
  'menu-right': MenuRightIcon,
  'menu-up': MenuUpIcon,
  'menu-variant': MenuVariantIcon,
  'menu': MenuIcon,
  'message-arrow-right-outline': MessageArrowRightOutlineIcon,
  'message-check-outline': MessageCheckOutlineIcon,
  'message-check': MessageCheckIcon,
  'message-minus-outline': MessageMinusOutlineIcon,
  'message-plus-outline': MessagePlusOutlineIcon,
  'message-text-outline': MessageTextOutlineIcon,
  'microphone-off': MicrophoneOffIcon,
  'microphone-outline': MicrophoneOutlineIcon,
  'microphone': MicrophoneIcon,
  'minus-box': MinusBoxIcon,
  'minus-circle-outline': MinusCircleOutlineIcon,
  'minus-circle': MinusCircleIcon,
  'minus': MinusIcon,
  'monitor-account': MonitorAccountIcon,
  'monitor-off': MonitorOffIcon,
  'monitor-share': MonitorShareIcon,
  'monitor': MonitorIcon,
  'not-equal-variant': NotEqualVariantIcon,
  'notebook-outline': NotebookOutlineIcon,
  'oauth': OauthIcon,
  'open-in-new': OpenInNewIcon,
  'palette-outline': PaletteOutlineIcon,
  'paperclip': PaperclipIcon,
  'pause': PauseIcon,
  'pencil-outline': PencilOutlineIcon,
  'phone-hangup': PhoneHangupIcon,
  'phone-in-talk': PhoneInTalkIcon,
  'phone-outline': PhoneOutlineIcon,
  'phone': PhoneIcon,
  'pin-outline': PinOutlineIcon,
  'pin': PinIcon,
  'play-box-multiple-outline': PlayBoxMultipleOutlineIcon,
  'play-outline': PlayOutlineIcon,
  'play': PlayIcon,
  'playlist-check': PlaylistCheckIcon,
  'plus-box-outline': PlusBoxOutlineIcon,
  'plus-box': PlusBoxIcon,
  'plus': PlusIcon,
  'pound': PoundIcon,
  'power-plug-outline': PowerPlugOutlineIcon,
  'product-boards': ProductBoardsIcon,
  'product-channels': ProductChannelsIcon,
  'product-playbooks': ProductPlaybooksIcon,
  'products': ProductsIcon,
  'radiobox-blank': RadioboxBlankIcon,
  'radiobox-marked': RadioboxMarkedIcon,
  'record-circle-outline': RecordCircleOutlineIcon,
  'record-square-outline': RecordSquareOutlineIcon,
  'refresh': RefreshIcon,
  'reply-outline': ReplyOutlineIcon,
  'resize-bottom-right': ResizeBottomRightIcon,
  'restore': RestoreIcon,
  'robot-happy': RobotHappyIcon,
  'search-list': SearchListIcon,
  'send-outline': SendOutlineIcon,
  'send': SendIcon,
  'server-outline': ServerOutlineIcon,
  'server-variant-plus': ServerVariantPlusIcon,
  'server-variant': ServerVariantIcon,
  'settings-outline': SettingsOutlineIcon,
  'share-variant-outline': ShareVariantOutlineIcon,
  'shield-alert-outline': ShieldAlertOutlineIcon,
  'shield-check': ShieldCheckIcon,
  'shield-lock-outline': ShieldLockOutlineIcon,
  'shield-outline': ShieldOutlineIcon,
  'shuffle-variant': ShuffleVariantIcon,
  'sitemap': SitemapIcon,
  'slash-forward-box-outline': SlashForwardBoxOutlineIcon,
  'slash-forward': SlashForwardIcon,
  'soccer': SoccerIcon,
  'sort-alphabetical-ascending': SortAlphabeticalAscendingIcon,
  'sort-ascending': SortAscendingIcon,
  'source-branch': SourceBranchIcon,
  'source-pull': SourcePullIcon,
  'spellcheck': SpellcheckIcon,
  'square': SquareIcon,
  'star-outline': StarOutlineIcon,
  'star': StarIcon,
  'sync': SyncIcon,
  'table-column-plus-after': TableColumnPlusAfterIcon,
  'table-column-plus-before': TableColumnPlusBeforeIcon,
  'table-column-remove': TableColumnRemoveIcon,
  'table-large': TableLargeIcon,
  'table-plus': TablePlusIcon,
  'table-remove': TableRemoveIcon,
  'table-row-plus-after': TableRowPlusAfterIcon,
  'table-row-plus-before': TableRowPlusBeforeIcon,
  'table-row-remove': TableRowRemoveIcon,
  'table-settings': TableSettingsIcon,
  'tablet': TabletIcon,
  'text-box-outline': TextBoxOutlineIcon,
  'text-long': TextLongIcon,
  'text-short': TextShortIcon,
  'thumbs-up-down': ThumbsUpDownIcon,
  'timeline-text-outline': TimelineTextOutlineIcon,
  'translate': TranslateIcon,
  'trash-can-outline': TrashCanOutlineIcon,
  'tune': TuneIcon,
  'update': UpdateIcon,
  'upload-outline': UploadOutlineIcon,
  'video-off-outline': VideoOffOutlineIcon,
  'video-outline': VideoOutlineIcon,
  'view-grid-plus-outline': ViewGridPlusOutlineIcon,
  'volume-high': VolumeHighIcon,
  'webhook-incoming': WebhookIncomingIcon,
  'webhook-outgoing': WebhookOutgoingIcon,
  'webhook': WebhookIcon,
} as const satisfies Record<string, CompassSvgIcon>;

export type StorybookIconName = keyof typeof STORYBOOK_ICONS;

export const STORYBOOK_ICON_NAMES = Object.keys(
  STORYBOOK_ICONS,
) as StorybookIconName[];
