import type {
  ConsoleSidebarCategoryData,
} from '@/components/ui/ConsoleSidebar/ConsoleSidebar';
import { createElement } from 'react';
import AccountMultipleOutlineIcon from '@mattermost/compass-icons/components/account-multiple-outline';
import SitemapIcon from '@mattermost/compass-icons/components/sitemap';
import ServerVariantIcon from '@mattermost/compass-icons/components/server-variant';
import type { DeviceSession, SessionAttribute } from './types';

export const DEFAULT_TTL = 30;
export const DEFAULT_GRACE = 60;

/** Sidebar matching the System Console pattern. */
export const SIDEBAR_CATEGORIES: ConsoleSidebarCategoryData[] = [
  {
    id: 'user-management',
    label: 'User Management',
    icon: createElement(AccountMultipleOutlineIcon),
    items: [
      { id: 'users', label: 'Users' },
      { id: 'groups', label: 'Groups' },
      { id: 'teams', label: 'Teams' },
      { id: 'channels', label: 'Channels' },
      { id: 'permissions', label: 'Permissions' },
      { id: 'system-roles', label: 'System Roles', tag: 'Beta' },
    ],
  },
  {
    id: 'system-attributes',
    label: 'System Attributes',
    icon: createElement(SitemapIcon),
    items: [
      { id: 'user-attributes', label: 'User Attributes' },
      { id: 'membership-policies', label: 'Membership Policies' },
      { id: 'permission-policies', label: 'Permission Policies' },
      { id: 'session-attributes', label: 'Session Attributes' },
    ],
  },
  {
    id: 'environment',
    label: 'Environment',
    icon: createElement(ServerVariantIcon),
    items: [
      { id: 'web-server', label: 'Web Server' },
      { id: 'database', label: 'Database' },
      { id: 'elasticsearch', label: 'Elasticsearch' },
      { id: 'file-storage', label: 'File Storage' },
      { id: 'image-proxy', label: 'Image Proxy' },
      { id: 'smtp', label: 'SMTP' },
    ],
  },
];

/** Pre-configured session attributes — full schema from tech spec §Schema. */
export const SESSION_ATTRIBUTES: SessionAttribute[] = [
  // ─── Network Identity ────────────────────────────────────────────────────
  {
    id: 'client_ip_address',
    displayName: 'Client IP Address',
    name: 'client_ip_address',
    type: 'IP',
    category: 'Network Identity',
    source: 'client',
    desktop: { state: 'available' },
    mobile: { state: 'available' },
    browser: { state: 'unavailable', detail: 'Browsers do not collect client-side IP; the server-observed ip_address attribute is the substitute.' },
    ttlSeconds: 30,
    gracePeriodSeconds: 60,
    enabled: true,
    policyCount: 12,
    notes: 'Client-reported primary non-loopback IP. Useful for detecting NAT/proxy discrepancies against server-observed ip_address.',
  },
  {
    id: 'network_interface_type',
    displayName: 'Network Interface Type',
    name: 'network_interface_type',
    type: 'Enum',
    category: 'Network Identity',
    source: 'client',
    desktop: { state: 'available' },
    mobile: { state: 'available' },
    browser: { state: 'unavailable' },
    ttlSeconds: 30,
    gracePeriodSeconds: 60,
    enabled: true,
    policyCount: 7,
    notes: 'WiFi / Ethernet / Cellular / VPN / Bluetooth / Other.',
  },
  {
    id: 'vpn_active',
    displayName: 'VPN Active Indicator',
    name: 'vpn_active',
    type: 'Boolean',
    category: 'Network Identity',
    source: 'client',
    desktop: { state: 'available' },
    mobile: { state: 'available', detail: 'iOS: via new RNUtils.isVpnActive() inspecting utun*/ipsec*/ppp* interfaces. Android: via NetInfo.' },
    browser: { state: 'unavailable' },
    ttlSeconds: 30,
    gracePeriodSeconds: 60,
    enabled: true,
    policyCount: 9,
  },
  {
    id: 'ssid',
    displayName: 'SSID (Network Name)',
    name: 'ssid',
    type: 'String',
    category: 'Network Identity',
    source: 'client',
    desktop: { state: 'caveats', detail: 'Windows: available via WlanQueryInterface. macOS: not collected — CoreWLAN requires the Location Services entitlement, deferred to v2.0.' },
    mobile: { state: 'caveats', detail: 'iOS: requires WhenInUse Location authorization (NEHotspotNetwork). Android: requires ACCESS_FINE_LOCATION. Returns null if permission denied.' },
    browser: { state: 'unavailable' },
    ttlSeconds: 30,
    gracePeriodSeconds: 60,
    enabled: true,
    policyCount: 2,
    notes: 'Low-trust signal; SSIDs are trivially spoofable. Useful for corroborating corporate-network detection.',
  },
  {
    id: 'server_fqdn',
    displayName: 'Server FQDN',
    name: 'server_fqdn',
    type: 'String',
    category: 'Network Identity',
    source: 'client',
    desktop: { state: 'available' },
    mobile: { state: 'available' },
    browser: { state: 'caveats', detail: 'Reported based on the URL the client is connected to.' },
    ttlSeconds: 60,
    gracePeriodSeconds: 60,
    enabled: true,
    policyCount: 4,
    notes: 'e.g., chat.il4.mattermost.com. Reverse-proxy-supplied recommended for high-assurance environments.',
    trustNote: 'Client-reported. For high-assurance, recommend reverse-proxy header injection.',
  },
  {
    id: 'client_fqdn',
    displayName: 'Client Machine FQDN',
    name: 'client_fqdn',
    type: 'String',
    category: 'Network Identity',
    source: 'client',
    desktop: { state: 'caveats', detail: 'Windows: GetComputerNameExW reliable when domain-joined. macOS: SCDynamicStoreCopyLocalHostName + active search domain; limited outside AD-style environments.' },
    mobile: { state: 'unavailable', detail: 'Phones are not domain-joined. The schema filters this attribute out of the mobile manifest.' },
    browser: { state: 'unavailable' },
    ttlSeconds: 3600,
    gracePeriodSeconds: 60,
    enabled: false,
    policyCount: 1,
    notes: 'e.g., coreys-laptop.division1example.mil. Enables device-division org scoping (where the device is domain-joined).',
  },
  {
    id: 'ip_address',
    displayName: 'IP Address (server-observed)',
    name: 'ip_address',
    type: 'IP',
    category: 'Network Identity',
    source: 'server',
    desktop: { state: 'available' },
    mobile: { state: 'available' },
    browser: { state: 'available' },
    ttlSeconds: 0,
    gracePeriodSeconds: 0,
    enabled: true,
    policyCount: 8,
    notes: 'Server-observed IP, honouring the configured trusted-proxy header. Always available — no TTL applies.',
    trustNote: 'Server-observed — high assurance for this signal.',
  },

  // ─── Device Identity ─────────────────────────────────────────────────────
  {
    id: 'device_id',
    displayName: 'Device ID (UUID)',
    name: 'device_id',
    type: 'String',
    category: 'Device Identity',
    source: 'client',
    desktop: { state: 'available', detail: 'macOS: IOPlatformUUID. Windows: SMBIOS Type 1 UUID.' },
    mobile: { state: 'available', detail: 'iOS: identifierForVendor. Android: ANDROID_ID.' },
    browser: { state: 'unavailable' },
    ttlSeconds: 86400,
    gracePeriodSeconds: 60,
    enabled: true,
    policyCount: 3,
    notes: 'Stable per-device identifier. Used by the device-ID consistency check (see Settings).',
    trustNote: 'Client-asserted — moderate assurance. Spoofable on a compromised device.',
  },
  {
    id: 'hardware_id',
    displayName: 'Hardware ID (serial)',
    name: 'hardware_id',
    type: 'String',
    category: 'Device Identity',
    source: 'client',
    desktop: { state: 'available', detail: 'macOS: IOPlatformSerialNumber. Windows: SMBIOS Type 1 serial.' },
    mobile: { state: 'caveats', detail: 'iOS: not collected — true serial requires MDM/DEP entitlements (deferred to v2.0). Android: requires MDM-level system permissions.' },
    browser: { state: 'unavailable' },
    ttlSeconds: 86400,
    gracePeriodSeconds: 60,
    enabled: false,
    policyCount: 2,
    notes: 'Distinct from device_id — this is the physical hardware serial. Subject to platform-privacy restrictions.',
    trustNote: 'Client-asserted — moderate assurance.',
  },
  {
    id: 'mdm_enrolled',
    displayName: 'MDM Enrollment Status',
    name: 'mdm_enrolled',
    type: 'Boolean',
    category: 'Device Identity',
    source: 'client',
    desktop: { state: 'available', detail: 'Windows: HKLM\\SOFTWARE\\Microsoft\\Enrollments. macOS: filesystem check of /Library/Managed Preferences — does not work on Mac App Store builds.' },
    mobile: { state: 'available', detail: 'iOS: isSupervised + managed-config payload. Android: DevicePolicyManager.' },
    browser: { state: 'unavailable' },
    ttlSeconds: 300,
    gracePeriodSeconds: 60,
    enabled: true,
    policyCount: 15,
    notes: 'Widely deployed in DoD C2C programs. Client-asserted — verify with PKI for stronger trust.',
    trustNote: 'Client-asserted, MDM-corroborated — moderate assurance.',
  },

  // ─── Device Posture ──────────────────────────────────────────────────────
  {
    id: 'os_platform',
    displayName: 'OS Platform',
    name: 'os_platform',
    type: 'Enum',
    category: 'Device Posture',
    source: 'client',
    desktop: { state: 'available' },
    mobile: { state: 'available' },
    browser: { state: 'unavailable' },
    ttlSeconds: 3600,
    gracePeriodSeconds: 60,
    enabled: true,
    policyCount: 5,
    notes: 'windows / macos / ios / android. Constant per-platform.',
  },
  {
    id: 'os_version',
    displayName: 'OS Version',
    name: 'os_version',
    type: 'Version',
    category: 'Device Posture',
    source: 'client',
    desktop: { state: 'available' },
    mobile: { state: 'available' },
    browser: { state: 'unavailable' },
    ttlSeconds: 3600,
    gracePeriodSeconds: 60,
    enabled: true,
    policyCount: 18,
    notes: 'Required for patch-level policy evaluation per DoD ZT RA v2.0.',
  },
  {
    id: 'client_version',
    displayName: 'Client Software Version',
    name: 'client_version',
    type: 'Version',
    category: 'Device Posture',
    source: 'client',
    desktop: { state: 'available' },
    mobile: { state: 'available' },
    browser: { state: 'unavailable' },
    ttlSeconds: 3600,
    gracePeriodSeconds: 60,
    enabled: true,
    policyCount: 4,
    notes: 'Version of the Mattermost client application itself.',
  },
  {
    id: 'jailbreak_detected',
    displayName: 'Jailbreak / Root Detection',
    name: 'jailbreak_detected',
    type: 'Boolean',
    category: 'Device Posture',
    source: 'client',
    desktop: { state: 'unavailable', detail: 'Desktop application integrity verification is a known gap in V1.' },
    mobile: { state: 'available', detail: 'Via expo-device isRootedExperimentalAsync, independent of the existing MobileJailbreakProtection setting.' },
    browser: { state: 'unavailable' },
    ttlSeconds: 300,
    gracePeriodSeconds: 60,
    enabled: true,
    policyCount: 8,
    notes: 'Mobile-only in V1. Desktop integrity gap — fail-secure when requested.',
  },

  // ─── User-Agent (server-native, carry-forward from v0.1) ────────────────
  {
    id: 'user_agent_platform',
    displayName: 'User-Agent Platform',
    name: 'user_agent_platform',
    type: 'String',
    category: 'User-Agent',
    source: 'server',
    desktop: { state: 'available' },
    mobile: { state: 'available' },
    browser: { state: 'available' },
    ttlSeconds: 0,
    gracePeriodSeconds: 0,
    enabled: true,
    policyCount: 2,
    notes: 'Parsed server-side from the request User-Agent. No TTL applies.',
    trustNote: 'Server-observed but spoofable (User-Agent is client-controlled).',
  },
  {
    id: 'user_agent_os',
    displayName: 'User-Agent OS',
    name: 'user_agent_os',
    type: 'String',
    category: 'User-Agent',
    source: 'server',
    desktop: { state: 'available' },
    mobile: { state: 'available' },
    browser: { state: 'available' },
    ttlSeconds: 0,
    gracePeriodSeconds: 0,
    enabled: true,
    policyCount: 1,
    notes: 'Parsed server-side from the User-Agent OS token.',
  },
  {
    id: 'user_agent_browser_name',
    displayName: 'User-Agent Browser Name',
    name: 'user_agent_browser_name',
    type: 'String',
    category: 'User-Agent',
    source: 'server',
    desktop: { state: 'available' },
    mobile: { state: 'available' },
    browser: { state: 'available' },
    ttlSeconds: 0,
    gracePeriodSeconds: 0,
    enabled: true,
    policyCount: 0,
    notes: 'e.g., Chrome, Desktop App, Mobile App.',
  },
  {
    id: 'user_agent_browser_version',
    displayName: 'User-Agent Browser Version',
    name: 'user_agent_browser_version',
    type: 'String',
    category: 'User-Agent',
    source: 'server',
    desktop: { state: 'available' },
    mobile: { state: 'available' },
    browser: { state: 'available' },
    ttlSeconds: 0,
    gracePeriodSeconds: 0,
    enabled: false,
    policyCount: 0,
  },
];

/** Sample active sessions for diagnostics view. */
export const SAMPLE_SESSIONS: DeviceSession[] = [
  {
    id: 's-1',
    deviceName: 'MacBook Pro M3 — Corey',
    platform: 'desktop',
    ip: '10.42.1.108',
    deviceId: 'A3F5-MBP-7821',
    lastRefresh: '2 minutes ago',
    attributeCount: 14,
  },
  {
    id: 's-2',
    deviceName: 'iPhone 15 Pro — Corey',
    platform: 'mobile',
    ip: '100.64.18.211',
    deviceId: 'iOS-IDFV-8A2C',
    lastRefresh: '14 minutes ago',
    attributeCount: 11,
  },
  {
    id: 's-3',
    deviceName: 'Chrome — desktop.example.com',
    platform: 'browser',
    ip: '203.0.113.42',
    deviceId: '—',
    lastRefresh: '30 seconds ago',
    attributeCount: 5,
  },
];

/** Per-session attribute values for the diagnostics master-detail view. */
export const SESSION_VALUES: Record<string, Record<string, string | boolean>> = {
  's-1': {
    client_ip_address: '10.42.1.108',
    network_interface_type: 'Ethernet',
    vpn_active: true,
    ssid: 'MM-Corp-A',
    server_fqdn: 'chat.il4.mattermost.com',
    client_fqdn: 'coreys-mbp.division1.example.mil',
    ip_address: '10.42.1.108',
    device_id: 'A3F5-MBP-7821',
    hardware_id: 'C02XD12345',
    mdm_enrolled: true,
    os_platform: 'macos',
    os_version: '14.4.1',
    client_version: '10.4.0',
    jailbreak_detected: false,
    user_agent_platform: 'darwin',
    user_agent_os: 'macOS 14.4.1',
    user_agent_browser_name: 'Desktop App',
    user_agent_browser_version: '10.4.0',
  },
  's-2': {
    client_ip_address: '100.64.18.211',
    network_interface_type: 'Cellular',
    vpn_active: true,
    ssid: '—',
    server_fqdn: 'chat.il4.mattermost.com',
    client_fqdn: '—',
    ip_address: '100.64.18.211',
    device_id: 'iOS-IDFV-8A2C',
    hardware_id: '—',
    mdm_enrolled: true,
    os_platform: 'ios',
    os_version: '17.4',
    client_version: '2.18.0',
    jailbreak_detected: false,
    user_agent_platform: 'ios',
    user_agent_os: 'iOS 17.4',
    user_agent_browser_name: 'Mobile App',
    user_agent_browser_version: '2.18.0',
  },
  's-3': {
    client_ip_address: '—',
    network_interface_type: '—',
    vpn_active: '—',
    ssid: '—',
    server_fqdn: '—',
    client_fqdn: '—',
    ip_address: '203.0.113.42',
    device_id: '—',
    hardware_id: '—',
    mdm_enrolled: '—',
    os_platform: '—',
    os_version: '—',
    client_version: '—',
    jailbreak_detected: '—',
    user_agent_platform: 'win32',
    user_agent_os: 'Windows 11',
    user_agent_browser_name: 'Chrome',
    user_agent_browser_version: '124.0.6367.92',
  },
};
